### ISSUE TITLE
Only valid bearer authentication supported

### ISSUE THREAD

**Issue by SaphirePI** [takomst/spotify-to-lavalink#1]
Your token is valide, but is missing `Bearer` prefix
Also:

1. i found thats token is not generating when using function, i generated it by same function, but used into eval (because of interval). You can generate it in 5 secs, then write that you generated it, and generate in 1 hour.

2. Bearer prefix is missing

3. fetch options is NOT updating when token is changing, you can do it in renewToken function

![image](https://nefelit.design/3190607e999aa0c0.png)

**Comment by Dolliwyx** [comment]
Hey thanks for checking out this repo, this issue has been resolved in https://github.com/takomst/spotify-to-lavalink/commit/0c5550d2240b8f81ab034826605b588f9289b5ce.
