### ISSUE TITLE
getTrack(), getAlbumTracks(), getPlaylistTracks() return null

### ISSUE THREAD

**Issue by ItzFireable** [takomst/spotify-to-lavalink#10]
## Expected Behavior
All of them should return a Lavalink object with the method used, with second variable being true.

## Current Behavior
Returns null, can't be used.

## Steps to Reproduce (for bugs)

1. `const curtrack = await client.spotify.getTrack(2yyT3q2OhnHeVTpbtp4rFU, true);`
2. `console.log("console returned " + curtrack)`
3. Console responds "console returned null"

## Your Environment

* Version used: Latest
* Node version: 15.8.0

Not sure what is causing this, everything is setup correctly, Lavalink nodes works on other parts of the code suck as the audio player and Spotify Client ID & Secret work in other projects.

**Comment by Dwigoric** [comment]
Hi @ItzFireable, do you have a working IP rotation? The value `null` is returned when the Lavalink node could not find a match for the Spotify track, which is often caused by 429s.

**Comment by ItzFireable** [comment]
There's no proxy system (or IP rotation, as you said it) set up for the Lavalink nodes yet. This was an issue since the start though, before a 429 could have occurred.

**Comment by Dwigoric** [comment]
Thanks for clarifying. Would it be possible to set up an IPv6 rotation (preferably using a /48 block) on your node(s) so we can rule out this possibility?

**Comment by ItzFireable** [comment]
This is something I'm not capable of doing at the moment as I'm not the host of the Lavalink server. Will contact our host about this, and see if that is possible.

Just to confirm, nothing should be wrong here? It's currently connecting to the second node out of our 3 nodes, and connected to our client. Making it it's own const made no difference.
![image](https://user-images.githubusercontent.com/38793386/113137368-1fd26d80-922d-11eb-8b13-6abf08083ab0.png)

**Comment by Dwigoric** [comment]
Yes, those seem to be correct. I recommend using a localhost or 127.0.0.1 node to minimize node connection issues.

**Comment by ItzFireable** [comment]
I'm aware, just connected to the nodes from my own computer like that due to the server being hosted elsewhere.

**Comment by Dolliwyx** [comment]
Hello! I was able to reproduce the steps you've given us. Although, I noticed that the Spotify track that you've queried (`2yyT3q2OhnHeVTpbtp4rFU`) didn't return any similar results related to the song on YouTube, hence it might be the reason for Lavalink to return `null`.
