### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Samir-OP** [takomst/spotify-to-lavalink#9]
## Current Behavior

```
{
  error: {
    status: 400,
    message: 'Only valid bearer authentication supported'
  }
}
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Node version:
* Link to your project (if applicable):

**Comment by Dwigoric** [comment]
Hi, thanks for opening an issue.

I have edited your issue according to our issue template. Please properly fill out the template so we can give your more assistance.

**Comment by Dwigoric** [comment]
Did you give the `SpotifyParser` class your Spotify client ID and Secret while instantiating it?

**Comment by Samir-OP** [comment]
yes

**Comment by Samir-OP** [comment]
fixed
